version: '3.3'

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:22.0.1"
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      DEBUG: "true"
      DEBUG_PORT: '*:8787'
    entrypoint: /bin/bash
    command: -c "/opt/keycloak/bin/kc.sh start"
    ports:
      - 8080:8080
      - "127.0.0.1:8787:8787"
    expose:
      - 8787
    volumes:
      - ./data/:/opt/keycloak/data/
      - ./deployments/:/opt/keycloak/providers/
    profiles:
      - run


  keycloak-import:
    image: "quay.io/keycloak/keycloak:22.0.1"
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      DEBUG: "true"
      DEBUG_PORT: '*:8787'
    entrypoint: /bin/bash
    command: -c "/opt/keycloak/bin/kc.sh import --dir /test-realm/"
    ports:
      - 8080:8080
      - "127.0.0.1:8787:8787"
    expose:
      - 8787
    volumes:
      - ./test-realm/:/test-realm/
      - ./data/:/opt/keycloak/data/
      - ./deployments/:/opt/keycloak/providers/
    profiles:
      - import